name: CI
on: [push]


env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build-api:
    name: Build and Unit Test API
    runs-on: ubuntu-latest
    env:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: ./gradlew api:build api:sonarqube -Dsonar.organization=default -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}
  build-ui:
    name: Build and Unit Test UI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: |
            ui/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/ui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: npm run test:ci
  e2e-desktop:
    name: End-to-End Tests - Desktop
    runs-on: ubuntu-latest
    needs: [build-ui, build-api]
    env:
      SPRING_PROFILES_ACTIVE: e2e
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v2
        with:
          path: |
            ui/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/ui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: |
          ./gradlew bootRun &
          cd ui
          npm run start &
          sleep 30
          npm run e2e-cypress:ci
      - uses: actions/upload-artifact@v2
        with:
          name: videos
          path: ui/build/cypress/videos/
  e2e-mobile:
    name: End-to-End Tests - Mobile
    runs-on: ubuntu-latest
    needs: [build-ui, build-api]
    env:
      SPRING_PROFILES_ACTIVE: e2e
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v2
        with:
          path: |
            ui/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/ui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: |
          ./gradlew bootRun &
          cd ui
          npm run start &
          sleep 30
          npm run e2e-cypress:ci-mobile
      - uses: actions/upload-artifact@v2
        with:
          name: videos-mobile
          path: ui/build/cypress/videos/
